/**
 * Staged entries for JS-rendered design system docs that the crawler cannot
 * parse: Adobe Spectrum and Google Material 3. Content extracted via research
 * agents (Spectrum from the embedded Next.js flight payload; Material via
 * headless-browser rendering). No backticks in content strings.
 *
 * Run: npx tsx scripts/build-staged-foundations.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'content/staged';
mkdirSync(OUT, { recursive: true });

interface Staged {
  slug: string; title: string; url: string; category: string;
  system: string; tags: string[]; content: string;
}

const ENTRIES: Staged[] = [
  {
    slug: 'spectrum-color-fundamentals',
    title: 'Spectrum Color Fundamentals: Perceptual Color Science in a Design System',
    url: 'https://spectrum.adobe.com/page/color-fundamentals/',
    category: 'tokens',
    system: 'Spectrum',
    tags: ['spectrum', 'adobe', 'color', 'color-science', 'contrast', 'accessibility', 'design-tokens'],
    content: `# Spectrum Color Fundamentals

Adobe Spectrum's color system is based on a foundation of visual perception, inclusive design, and accessibility. It is the most explicitly science-grounded color documentation of any major design system.

## Vocabulary (chosen intentionally)

**Color token**: "A design token that's specific to color usage. This provides a way of referencing a variable color value (a color value that changes based on color theme). Color tokens are named by the color and a number representing an index in the list of tints and shades. For example, blue-400 represents the fourth color in the list of tints and shades of blue."

**Contrast ratio**: "The measurable difference in lightness between two comparative color values using the WCAG relative luminance formula." **Target contrast ratio**: "The desired contrast ratio between two color values when one of the color values is generated by a color tool."

**Color theme**: "The full set of color tokens and their color values relative to a specific background color."

## Themes are not device modes

"Color themes and device color modes are not the same thing. Color themes are app-specific options, while device color modes are operating system settings... Spectrum offers three color themes: light, dark, and darkest. These themes are available in light and dark device color modes."

In device light mode, Spectrum offers light and dark themes — "Dark theme is an option for experiences that are optimal with a darker interface regardless of the device mode, such as photo and video editing." In device dark mode there is a single default: darkest, aligning with OS dark modes' black backgrounds.

## Contrast-generated colors — the core mechanism

"Spectrum's color themes are generated using target contrast ratios with a specified background color. Certain color tokens' values are generated with confidence that they will meet or exceed specific WCAG AA contrast minimums. As the color token name increases in number (e.g., blue-700, blue-800, blue-900), the color value's contrast with the background also increases. Because of this, colors progressively get darker in light theme and lighter in dark themes."

The palette is computed from contrast targets, not hand-picked — which is why the same token index carries the same accessibility guarantee in every theme.

## Uniform color space

"Spectrum's colors have been evaluated using the CIECAM02-UCS (CAM02) uniform color space... Spectrum avoids using color spaces that are non-uniform (such as HSL) for authoring and evaluating colors — whether related to color harmonies, or the transitions each color makes from light to dark... Balanced progressions in a non-uniform color space may result in imbalanced colors."

## Perceptual phenomena the system accounts for

**Chromatic luminance (Helmholtz-Kohlrausch effect)**: "As colors increase in saturation, they appear to have a brighter luminosity... Spectrum does not try to adjust for the effects of chromatic luminance in its color system... this perceived lightness should not be prioritized over calculated measurements for contrast."

**Stevens' power law**: "Numerically even distributions of tints and shades (in a perceptually uniform color space) will not appear to be equally distributed. Perceptually even distributions follow a power scale. Spectrum's color system accommodates for this by following a curved lightness distribution. This provides a more balanced rate of change, which ensures that colors for interactive states appear uniform."

**Chromatic adaptation**: "Humans compensate for color based on the environmental setting... Spectrum uses fully desaturated grays to prevent the misinterpretation of colors due to chromatic adaptation caused by the user interface."

**Simultaneous contrast**: "Adjacent colors influence each others' appearance... Spectrum uses fully desaturated grays, and uses color sparingly to prevent the effects of simultaneous contrast from influencing image manipulation workflows."

The desaturated-gray decisions are domain-driven: Adobe's products are imaging tools, and the UI must never bias the user's perception of their own content.

## Gamut caveat

"RGB colors will appear less saturated when comparing sRGB display to wide-gamut DCI-P3 display. Spectrum is not color managed, meaning that colors will appear differently based on a user's device."`
  },
  {
    slug: 'spectrum-design-tokens',
    title: 'Spectrum Design Tokens: Flat Human-Readable Naming and the Alias-First Rule',
    url: 'https://spectrum.adobe.com/page/design-tokens/',
    category: 'tokens',
    system: 'Spectrum',
    tags: ['spectrum', 'adobe', 'design-tokens', 'naming', 'aliases', 'architecture'],
    content: `# Spectrum Design Tokens

## Definition

"Design tokens — or tokens, for short — are design decisions, translated into data. They're ultimately a communication tool: a shared language between design and engineering for communicating detailed information about how to build user interfaces."

"We use tokens instead of hard-coded values so Spectrum can scale and support the complex ways that Adobe products need to intersect as a cohesive ecosystem."

## The philosophy: focused, not exhaustive

"Our design token system prioritizes predictability and flexibility. The overall methodology is to have a **focused set of tokens rather than all possible tokens for all possible scenarios.**"

And an honest scope statement rare in token documentation: "tokens only provide some — if not most — of the information needed to represent or implement a UI component. The token system is one resource in Spectrum's offerings rather than a complete knowledge set."

## Token types

- **Token**: a design decision represented as data, with a carefully chosen name.
- **Value**: the data associated with the name — either another token (an alias) or a final value. Examples: picker-border-width resolves to border-width-100; alert-dialog-minimum-width resolves to 288px.
- **Alias**: "A token that references another token, instead of referencing a hard-coded value." Example: negative-border-color-default resolves to negative-color-900.
- **Component-specific token**: scoped to one component. Examples: tooltip-maximum-width (160px desktop / 200px mobile); divider-thickness-small (1px).
- **Global token**: used across the system. Examples: corner-radius-75 (2px); component-height-100 (32px desktop / 40px mobile).

## Naming principles

"Spectrum names design tokens very intentionally and strategically":

- **Human-readable.** "Our tokens are communication tools that humans need to be able to readily understand... We do this to support our diverse array of product stakeholders — not just designers and engineers."
- **Flat structure.** "We use a flat structure — not a nested or tree structure — so that we aren't prioritizing a particular coding construct. This is also so that token names can have a narrative, conversational feel."
- **Predictable and flexible.** "We follow a token naming structure that maps to a natural language convention and uses a set vocabulary."

## The 3-part naming structure

"We use a 3-part structure for coming up with token names: **context, common unit, and clarification**. It's based on a common model for human language and narrative-building where the information communicated becomes increasingly granular."

Worked example: checkbox-control-size-small — "A checkbox is a component, and the most high-level or broad concept. A control is a common (consistent) unit; there are many different kinds of controls in the system. control-size is also a common unit... small is a particular size from a set of available sizes (t-shirt sizes), so it's the most detailed information being communicated in the token name."

Even spacing tokens read narratively: action-button-edge-to-hold-icon-large — the component, then the layout construct phrased descriptively ("the edge of the action button to the hold icon"), then the size.

## Usage rules

**"Only use global tokens when there are no available aliases for your use case."** Global tokens are the building blocks but "the least tied to the logic of our design language."

**"Use aliases wherever they can apply."** "They're a shared language for understanding Spectrum, and they help to associate meaning, context, and intent to the design tokens you're applying to your product. Using aliases is a good way to ensure that your product can evolve alongside Spectrum as the design system evolves, and to minimize future maintenance."

**Component-specific tokens stay with their component.** "It's not recommended to use component-specific tokens interchangeably with other components, unless one is derivative of the other."

Token source: github.com/adobe/spectrum-tokens. "Adobe product teams don't use the output of them directly, but instead use common UI frameworks, which includes the implementation of tokens into components."

Note the contrast with Material's md.sys.color.primary-style dotted hierarchy and Fluent's two-layer model: Spectrum deliberately rejects nesting so names read as sentences. All three converge on the same alias-over-raw-value rule.`
  },
  {
    slug: 'spectrum-inclusive-design',
    title: 'Spectrum Inclusive Design: Line Length, High Contrast Mode, and Error Prevention',
    url: 'https://spectrum.adobe.com/page/inclusive-design/',
    category: 'accessibility',
    system: 'Spectrum',
    tags: ['spectrum', 'adobe', 'accessibility', 'inclusive-design', 'high-contrast', 'typography'],
    content: `# Spectrum Inclusive Design

"Inclusive design is part of Adobe's mission... From how components function to language and internationalization, we consider inclusion to be a top priority."

## Structure

"Ensure that complex components — such as lists, forms, and panels — have a logical reading order. Check that the keyboard tab order has been defined in a logical progression."

## Color

"Use the Adobe Color set of tools to test your interface. You can also use the soft-proofing settings for colorblindness in Photoshop and Illustrator. Avoid referring to objects by color (or by location) alone. Instead, refer to these by their names or by the grouping in which they belong."

## Windows high contrast mode — a first-class requirement

"Windows high contrast mode is a setting that replaces all colors in the operating system to a simplified high contrast color palette... This is an important feature for users with low vision, contrast sensitivity, and other needs, and should be supported by all Adobe web-based and Windows applications."

"Spectrum component documentation will include visual references for what the component should look like in Windows high contrast mode."

Spectrum is one of very few systems that documents per-component high-contrast-mode appearance — most systems treat forced-colors mode as an afterthought.

## Fonts and text — specific numbers

- "Use one column per page, with a width no longer than **80 characters (or 40 CJK characters)** wide."
- "Have line lengths at a maximum of **50-75 characters**."
- "Left-align running text (this will be mirrored along with the UI for right-to-left languages)."
- "Fully-justified text creates **text rivers**, or irregular alignment of spaces that creates running gaps throughout the text; this makes it more difficult for readers with dyslexia."
- "Avoid switching alignments in a single view."
- "Whenever possible, provide options for people to adjust font size, color themes, and contrast."

## Error prevention over error messaging

"**Avoid the need for error messages by designing workflows that prevent an error state from even happening in the first place.**"

When there is an error: "associate it with the field or element that needs to be corrected or addressed. Make errors visually and semantically different from other messages (e.g., including icons, colors, placement), and write error messaging in a helpful and guiding way."

Also: "Use appropriate click/touch zones to leave enough space between elements... Anticipate spelling mistakes in search queries, and accommodate multiple spellings of words in search results."

## Keyboard equivalents

"Ensure that people can complete any action using a keyboard and keyboard equivalents, **including on mobile** (e.g., iPad Smart Keyboard). Set a tab order so that people can move back and forth within a view by using the Tab key. Use the built-in keyboard focus states that are defined in Spectrum components."

The mobile-keyboard requirement is notable: most systems' keyboard guidance stops at desktop.`
  },
  {
    slug: 'material-dynamic-color-hct',
    title: 'Material 3 Dynamic Color: HCT, Tonal Palettes, and Contrast by Construction',
    url: 'https://m3.material.io/styles/color/system/how-the-system-works',
    category: 'tokens',
    system: 'Material',
    tags: ['material-design', 'google', 'color', 'hct', 'dynamic-color', 'design-tokens', 'accessibility'],
    content: `# Material 3: How the Color System Works

## The paint-by-number model

"Imagine your product screen as a paint-by-number canvas: Each element on the screen has a number. Each number is assigned a color. You can hand-pick a color for every 'number' to create a static color scheme. But now, you can also use Material's dynamic color system to automatically generate an entire palette of accessible colors for each 'number' from a single source. This source can be a user's wallpaper, or in-app content like imagery. If the source changes, the product colors update to match."

**Color role** — "Like the 'numbers' on a paint-by-number canvas, color roles are assigned to specific UI elements. They have semantic names like primary, on primary, and primary container, and matching color tokens." There are **26 color roles** across light and dark themes.

## The dynamic color pipeline

"The dynamic color process is automatic. A single source color is used to generate five key colors, which are used to make tonal palettes. Tones from the palettes are then assigned to color roles, which are in turn assigned to elements of the UI."

1. **Source color** — from a user's wallpaper (analyzed through quantization), from in-app content (album art, logo, video preview), or hand-picked by a designer.
2. **Algorithm** — powered by Material Color Utilities (MCU), "a set of color libraries containing algorithms and utilities that develop color themes and schemes in your app."
3. **Five key colors** — the algorithms manipulate the source's hue and chroma to generate Primary, Secondary, Tertiary, Neutral, Neutral variant.
4. **Tonal palettes** — the system manipulates tone and chroma to create a tonal palette per key color, numbered 0 to 100 in increments of 10, plus 95, 98, and 99.
5. **Role assignment** — "The algorithm uses accessible color relationships to assign specific tones to the 26 color roles in both light and dark theme. For example, the algorithm assigns the color tone primary40 to the primary role and the tone primary100 to the on primary role. Dark theme colors are also automatically assigned so that apps receive both light and dark themes through a single set of color roles."

## Tone difference IS contrast — the load-bearing insight

"Because tone can describe the lightness or darkness of a color, it's used to define accessible color relationships. For example, the algorithms assign a dark tone to a button's container color and a light tone to its label color, ensuring that the colors have a 3:1 contrast. For even more contrast, the algorithms assign tones even farther apart, achieving a 7:1 contrast. This is the concept powering user-controlled contrast features."

Three contrast levels ship from the same roles: "Standard (default), Medium, High. Medium contrast provides a minimum contrast ratio of 3:1 for those who need more contrast, but may experience visual discomfort with higher contrasts from effects like halation. High contrast further emphasizes essential elements with a 7:1 contrast ratio."

## HCT — the color space that makes it possible

"The system uses a color space called HCT, which defines all colors using three dimensions: hue, chroma, and tone. Unlike other color spaces (like HSL or RGB), HCT allows the manipulation of a color's hue and chroma without affecting its tone."

- Hue: 0-360
- Chroma: "how colorful or neutral a color appears, quantified from 0 to infinity, though chroma values in HCT top out at roughly 120"
- Tone: "how light or dark a color appears, quantified from 0 (pure black, no luminance) to 100 (pure white). **Tone is crucial for visual accessibility because it determines contrast.**"

Warning from the docs: "HCT isn't interchangeable with other color spaces: values from models like HSL won't perfectly map to Material's HCT. Don't conflate color spaces when inspecting or adjusting colors. Colors with the same perceived brightness share the same tone value in HCT, but can have different HSL lightness values."

Physical honesty: "Color has physical limitations... some hues cannot exist with certain chroma or tones. Color limitations are the reason colors such as bright light blue or bright light red are not quite possible."

Compare Spectrum (CIECAM02-UCS, contrast-generated indexes) and Radix Colors (12 positional steps with APCA targets): three different architectures converging on the same principle — accessibility guaranteed by construction of the palette, not by per-use checking.`
  },
  {
    slug: 'material-design-tokens',
    title: 'Material 3 Design Tokens: Reference, System, and Component Token Classes',
    url: 'https://m3.material.io/foundations/design-tokens/overview',
    category: 'tokens',
    system: 'Material',
    tags: ['material-design', 'google', 'design-tokens', 'architecture', 'theming', 'naming'],
    content: `# Material 3 Design Tokens

"Design tokens are the building blocks of all UI elements. The same tokens are used in designs, tools, and code."

"A design token consists of 2 things: A code-like name, such as md.ref.palette.secondary90, and an associated value, such as #E8DEF8. The token's value can be one of several things: a color, typeface, measurement, or even another token."

## Why

"Tokens make it possible for a design system to have a single source of truth – a repository where style choices are recorded and changes can be tracked... By using tokens for design and implementation, style updates propagate consistently through an entire product or suite of products. They also help designers and engineers 'speak the same language,' reducing confusion during handoff."

"For example, if a designer's mock-ups and an engineer's implementation both reference the same token for the 'secondary container color,' then they can be confident that the same color is being used in both places. This applies even if the hex value assigned to that token gets updated."

## When tokens are NOT worth it — rare vendor honesty

"Tokens will be less helpful if: You have an existing app using hard-coded values that is unlikely to change in the next year or two. Your product does not have a design system."

## Name grammar

"The parts of a token name are separated by periods and proceed from the most general information ('md') to the most specific ('on-secondary'). All token names in a design system start with the system name... An abbreviation for the token class: 'ref' for reference tokens, 'sys' for system tokens, and 'comp' for component tokens."

Example: md.comp.fab.primary.container.color sets the container color for a FAB.

## The three classes

**Reference tokens (ref)** — "all of the style options available in a design system. They usually point to a static value – such as a color hex code or font size – but can also point to other reference tokens. **Reference tokens don't change based on context.**" They are the approved menu of options.

**System tokens (sys)** — "the decisions that systematize the design language for a specific theme or context. System tokens define the purpose a reference token serves in the UI. **This is where theming occurs.** The system token can point to different reference tokens depending on the context, such as a light or dark theme. Whenever possible, system tokens should point to reference tokens rather than static values."

**Component tokens (comp)** — "the elements required to compose a component, such as containers, label text, icons, states, and their values such as size, shape, color, or elevation. Whenever possible, component tokens should point to a system or reference token, and not contain hardcoded values."

"With three classes of tokens, teams can update design decisions globally or apply a change to a single component."

Honest scope note: "Not every stylistic choice of a component will be able to be expressed as a token, but whenever a design choice applies to multiple components of similar intent, a token should be used."

## Contexts

"Tokens can point to different values depending on a set of conditions. These conditions are called contexts and their resulting values are called contextual values. Examples of different contexts include: device form factors, dark theme, dense layouts, and right-to-left writing systems. You can think of a context as a kind of tag. If a token value is tagged with dark theme then it will override the default token value in a dark theme context."

This is the same three-tier shape as Brad Frost's tier-1/2/3 and Fluent's global/alias — Material adds the dotted grammar (md.{ref|sys|comp}) and the contexts mechanism as the formal override model.`
  },
  {
    slug: 'material-motion-physics',
    title: 'Material 3 Motion Physics: Springs Replace Easing and Duration',
    url: 'https://m3.material.io/styles/motion/overview/how-it-works',
    category: 'tokens',
    system: 'Material',
    tags: ['material-design', 'google', 'motion', 'springs', 'design-tokens', 'animation'],
    content: `# Material 3 Motion Physics System

"Material introduced the motion physics system with M3 Expressive. This new physics-based system makes interactions and transitions feel more alive, fluid, and natural... **The physics system is replacing the previous system based on easing and duration.**"

This is a significant break: a generation of design systems encoded motion as duration + easing-curve token pairs. Material now argues that model is obsolete.

## Motion schemes

"The physics system has two preset motion schemes: expressive and standard. The motion scheme you choose defines how your product feels."

- **Expressive** — "Material's opinionated motion scheme, and should be used for most situations, particularly hero moments and key interactions. The expressive motion scheme overshoots the final values to add bounce."
- **Standard** — "feels more functional with minimal bounce, and should be used for utilitarian products. The standard motion scheme eases into the final values."

Custom schemes are possible while still leveraging theming.

## Springs

"A spring is a combination of three attributes which control all motion behavior: **stiffness, damping, and initial velocity.**"

"Springs are versatile. One spring can apply to many situations, such as transitions, button effects, or gestures. This makes the motion and expression feel consistent throughout the product. Springs feel natural... They handle gestures, interruptions, and retargeting animations seamlessly."

"All component motion is driven by two tokens: expressive fast spatial and expressive fast effects."

## The token grammar

Token form: md.sys.motion.spring.fast.spatial

"Notice that the 'expressive' scheme isn't part of the token itself. Rather, **it's called at the product level and applied to all tokens. This makes it easier to swap schemes without changing assigned tokens.**"

Each scheme has three speeds (fast, default, slow) for two types of movement:

- **Spatial** springs — "for animations that move something on screen, for example the x and y position, rotation, size, rounded corners. This spring overshoots the final value and bounces into place."
- **Effects** springs — "to animate properties such as color and opacity animations, **where there shouldn't be any overshoot.**"

## Speed selection rules

- **Default**: "animations that partially cover the screen, such as bottom sheet and expanded navigation rail"
- **Fast**: "small components, such as switches and buttons; color change of the switch handle"
- **Slow**: "full-screen animations; full-screen content refresh"

Device adaptation: "Spring tokens work across devices... the exact values of each token differ depending on if the device is a wearable, phone, or tablet. This ensures the movement feels fast in the context of the device."

## Adoption levels

"Level 1: Use a default motion scheme... Level 2: Create a custom motion scheme (a custom MotionScheme object returning different AnimationSpec per property)... Level 3: Swap the default motion scheme per element (override the CompositionLocal for that particular composable)."

On Jetpack Compose, 21 Material components use the physics system by default.

## Why this matters beyond Material

Motion has been the least-systematized token category — the layer contracts and DTCG discussions handle color and dimension well, motion poorly. Material's answer (scheme applied at product level, spatial/effects split, speed mapped to element size) is the most complete motion-token architecture published, and pairs with Figma Motion's variables-with-modes as evidence that motion is becoming a governed design token category rather than per-screen craft.`
  },
];

let written = 0;
for (const e of ENTRIES) {
  writeFileSync(join(OUT, `${e.slug}.json`), JSON.stringify({
    id: `foundations-${e.slug}`,
    title: e.title,
    source: { type: 'url', location: e.url, ingested_at: new Date().toISOString() },
    content: e.content,
    chunks: [],
    metadata: {
      category: e.category, tags: e.tags, confidence: 'high', system: e.system,
      source_url: e.url, authority: 'primary',
      research_batch: 'foundations-2026-08', last_updated: new Date().toISOString(),
    },
  }, null, 2));
  written++;
}
console.log(`wrote ${written} staged entries`);
for (const e of ENTRIES) console.log(`  ${String(e.content.length).padStart(6)}  ${e.title.slice(0, 66)}`);
