/**
 * Generates staged ContentEntry files for the AI UI-generator research batch:
 * how Lovable, v0, Figma Make, and Replit each ingest a design system.
 *
 * Run: npx tsx scripts/build-staged-aitools.ts
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const OUT = 'content/staged';
mkdirSync(OUT, { recursive: true });

interface Staged {
  slug: string;
  title: string;
  url: string;
  category: string;
  system?: string;
  tags: string[];
  authority: string;
  content: string;
}

const ENTRIES: Staged[] = [
  {
    slug: 'lovable-design-systems',
    title: 'Lovable Design Systems: .lovable Folder, Schema, and the File-Copy Model',
    url: 'https://docs.lovable.dev/features/design-systems',
    category: 'tools',
    system: 'Lovable',
    tags: ['lovable', 'ai-generation', 'design-systems', 'component-library', 'design-tokens', 'ai-tools'],
    authority: 'primary',
    content: `# Design Systems in Lovable

Design systems in Lovable are **dedicated projects** acting as a single source of truth across a workspace. The design system *is* a Lovable project that other projects connect to — not a config file bolted onto an app.

## The .lovable folder

    .lovable/
    ├── design-system.json          # machine-readable schema
    ├── system.md                   # hand-authored guidelines
    └── rules/
        ├── components.md           # rendered documentation
        ├── design-tokens.md        # token reference
        └── library-guidelines.md   # stack requirements

design-system.json is generated by Lovable; the three rules/*.md files are rendered from it. system.md is the exception and the file practitioners own: it is "preserved across releases, meaning that Lovable does not regenerate it from the schema." It is meant to hold design philosophy and installation context.

## Two component distribution models

**Path A — local source.** Components live in the design system project. Tokens are discovered from "top-level styling files: CSS custom properties in files like src/index.css" or tailwind.config. Components export from src/index.ts or live under src/components/.

**Path B — npm wrapper.** The project wraps an external published package and Lovable reads "the component surface from the package's published type definitions." Private registries need scoped packages with .npmrc auth backed by workspace build secrets:

    @scope:registry=https://your-registry.example.com
    //your-registry.example.com/:_authToken=\${NPM_TOKEN}

## Attachment is file copy, not a dependency

When a design system is attached to a project:
- Components copy to src/design-system/<design-system-slug>/
- Knowledge files copy to .lovable/rules/libraries/<design-system-slug>/
- Dependencies merge into package.json
- A [[libraries]] entry in lovable.toml records the connection and version

This is the architecturally distinctive choice: Lovable vendors the design system into each consuming project rather than referencing it. Consequences follow directly — "A project can be connected to at most one design system at a time"; removing a design system severs updates and "copied files become ordinary editable code"; and local edits under src/design-system/ persist only until the next update is accepted, then are clobbered.

## Versioning

Every release bumps a version. Connected projects see an "Update available" prompt in chat. Accepting reruns the file copy against the new version. Draft design systems cannot seed new projects — release first.

## Exclusions

.dsignore controls what does not propagate. Excluded by default: showcase pages (src/pages/, src/routes/, *.stories.ts), test files, and scaffold entrypoints (src/main.tsx, src/App.tsx). Knowledge files in .lovable/rules/*.md always propagate.

## Setup verification

After attachment Lovable runs automatic verification checking "configuration, CSS imports, theme providers, dependencies, and import paths." Notably "verification turns are billed at zero credits" — Lovable does not charge for remediating its own wiring.

## Framework support and gating

"Lovable design systems support React-based component libraries out of the box." Vue, Angular, and Svelte require CSM/FDE consultation. Practitioner reporting indicates the feature is Enterprise-plan gated.

## Reported failure modes

Because attachment is an agent-executed file copy plus dependency merge rather than a deterministic package install, outcomes vary between runs. Practitioners report new projects scaffolding "on a TanStack template even when the design system is a Vite/React one," and the styling framework not always wired into the build automatically — the specific case being "Tailwind 3 pulling in and conflicting with Tailwind 4." This is the concrete cost of the dependency-merge model versus pinned peer dependencies, and explains why the zero-credit verification step exists.`
  },
  {
    slug: 'v0-design-systems-2',
    title: 'v0 Design Systems 2.0: Design System as a Skill, v0.json Configuration',
    url: 'https://v0.app/docs/design-systems-2',
    category: 'tools',
    system: 'v0',
    tags: ['v0', 'vercel', 'ai-generation', 'design-systems', 'skills', 'ai-tools', 'component-library'],
    authority: 'primary',
    content: `# v0 Design Systems 2.0

"Design Systems 2.0 lets you teach v0 your design system once, so chats can build with your real components, tokens, and conventions."

The abstraction change from v0's legacy registry approach: a design system is saved as a **skill** in your current scope (team or personal workspace). Skills are focused instruction sets v0 keeps with your work and applies when relevant.

## Required sources

- Installable npm package, .tgz/.tar archive, or source directory
- Design system repository or package containing components and tokens
- **A real app consuming the system** (shows providers, styles, fonts, setup)
- Storybook, docs, or design guidelines
- Figma frames or nodes for visual reference
- Private package credentials (as Development shared environment variables)
- Installation instructions and usage examples

## Import process

1. Add sources on the Design Systems page: GitHub repos, Figma frames/nodes, links, attachments
2. Add environment variables for private packages (requires Developer role on Vercel minimum)
3. Add notes about global styles, providers, fonts, deprecated components, conventions
4. Review the starter app v0 builds before saving
5. Approve and save the skill

## v0.json

    {
      "version": 1,
      "referenceWorkspace": {
        "sources": [
          {
            "id": "github-repo:owner/repo:main",
            "type": "github-repo",
            "repo": { "org": "owner", "name": "repo" },
            "ref": "main",
            "mountPath": "/vercel/share/v0-reference-workspace-sources/owner/repo/main"
          }
        ]
      },
      "environment": {
        "providers": [
          { "type": "shared-env-vars", "ids": ["env_var_id"] }
        ]
      },
      "starter": {
        "source": "skill-directory",
        "path": "assets/starter"
      }
    }

- version — schema version (use 1)
- referenceWorkspace.sources — **up to three** read-only GitHub sources, each with repo, ref, id, mount path. The three-source cap is a real constraint for multi-repo design systems.
- environment.providers — env var linking, typically shared-env-vars with Development IDs, or vercel-project with a projectId
- starter — application template: skill-directory, v0-default, or empty

## Using and updating

Saved skills appear on the Design Systems page. Attach from the prompt toolbar or reference in prompts. "Team owners on paid plans can choose a default design system for the team"; manual selections override the default.

Update by asking v0 in any chat to apply changes; v0 re-validates the starter app. Critically: "existing projects retain their original code; only new chats pick up the updated version." v0 does not retroactively migrate generated work.

## Access control

On paid team plans, owners can restrict skill creation/editing to "Owners and selected members." All members can still view and use skills. Only team owners set defaults.

## Best practices

- Include both the source and at least one real consumer app
- Prefer current docs and working examples over stale references
- Document global setup: "providers, theme wrappers, fonts, CSS imports, Tailwind config, and required environment variables"
- Keep sources focused on one design system and framework stack
- Pin GitHub sources to branches/refs and package versions in package.json

The "include a real consumer app" guidance is the practically important one: v0 is stating that a component package alone does not convey providers, theme wrappers, and global CSS setup — the agent learns those from an example app, not from the library.`
  },
  {
    slug: 'v0-shadcn-registry-legacy',
    title: 'v0 Registry-Based Design Systems: shadcn Registry as AI Context Transport',
    url: 'https://v0.app/docs/design-systems-legacy',
    category: 'tools',
    system: 'v0',
    tags: ['v0', 'shadcn', 'registry', 'design-tokens', 'mcp', 'ai-tools', 'design-systems'],
    authority: 'primary',
    content: `# v0 Registry-Based Design Systems (legacy)

Flagged as superseded by Design Systems 2.0, but still the best documentation of the registry mechanism — which remains how shadcn-based systems are distributed to *other* agents.

## What a registry is

A registry functions as "a distribution specification designed to pass context from your design system to AI Models," allowing v0 to generate prototypes matching your design system without manual overrides.

The framing matters: the registry is not a package manager, it is a **context transport aimed at models**.

## shadcn framing

"shadcn/ui is not a component library but rather a toolkit for building one." It provides direct source-code access, which is what makes it tractable for AI-generated customization — the model edits source rather than fighting a compiled component's API.

## Customization

**Colors** — modify src/app/tokens.css following "the shadcn/ui CSS variables standard."

**Fonts** — update src/app/layout.tsx using next/font/google or @font-face. Standard variables are --font-sans, --font-mono, --font-serif.

**Custom components** — add entries to registry.json following the registry-item specification. Entries specify registryDependencies for component references, and a files property with local paths and target deployment locations. The registry must include baseUrl and full route URLs pointing to your deployed instance.

## The load-bearing limitation

Stated by Vercel itself: **"v0 is specifically trained on the default implementations of the shadcn/ui components and may struggle with any customizations."**

This is the single most important caveat in the v0 design-system story. The closer your system is to stock shadcn, the better v0 performs; heavily customized systems degrade generation quality. It is a trained-prior problem, not a config problem, so no amount of registry metadata fully fixes it.

## Tailwind support

"v0 supports tailwind configs and globals.css files, you can use custom utility classes and CSS variables in your generations."

## MCP integration

The same registry serves v0 and third-party agents — the portability argument for the registry format over proprietary skill formats:

    {
      "mcpServers": {
        "shadcn": {
          "command": "npx",
          "args": ["-y", "shadcn@canary", "registry:mcp"],
          "env": {
            "REGISTRY_URL": "https://registry-starter.vercel.app/r/registry.json"
          }
        }
      }
    }

This provides "centralized, AI-native context on your design system and components."

## Figma integration (Jan 2025 guidance)

v0 extracts context from Figma files to inform generation. The documented recommendation is to break designs into smaller components in separate frames — navigation bars, sidebars, forms, individual landing page sections — and iterate component-by-component before combining into pages.

Note what this implies: Figma import in v0 is a **visual** context channel, not a structured token or component-instance channel. There is no documented mapping from Figma component instances to code components; that is Code Connect's job, and Code Connect is a Figma product, not a v0 one.`
  },
  {
    slug: 'figma-make-kits',
    title: 'Figma Make Kits: npm Packages, Library Variables, and Guidelines',
    url: 'https://help.figma.com/hc/en-us/articles/39241689698839-Get-started-with-Make-kits',
    category: 'tools',
    system: 'Figma',
    tags: ['figma', 'figma-make', 'make-kits', 'design-tokens', 'ai-generation', 'design-systems', 'variables'],
    authority: 'primary',
    content: `# Figma Make Kits

Make kits "enable teams to jump straight into building designs and prototypes in Make that are realistic to how your product looks and functions without having to add code and style context from scratch."

Rolled out to all paid plans beginning March 26, 2026; announced April 2, 2026. Guidance older than roughly Q1 2026 describing Figma Make as design-system-blind is stale.

## Three content types

1. **npm packages** — providing code context
2. **Variables and styles** — imported from published Figma Design libraries
3. **Guidelines** — instructions helping Make understand how to use system assets

This tri-partite structure is the distinguishing feature versus every other AI generator: **Figma is the only tool that can pull design tokens directly from the design source of truth** (published library variables) *and* the production component code (npm), and reconcile them with prose guidelines. Every other tool derives tokens from code only.

## Creation workflow

1. Start a new kit (assemble existing resources or build from scratch)
2. Add npm packages and/or library styles
3. Configure custom settings if needed
4. Write guidelines (critical for accurate results)
5. Test the kit thoroughly
6. Publish to organization via the "Publish kit" button

Guidelines require special attention for: explaining token quirks, organizing decisions logically, documenting typography completely, establishing color token hierarchy, stating constraints, and providing code composition examples. The emphasis on "token quirks" and "color token hierarchy" is telling — Figma acknowledges that raw variable export is insufficient and semantic intent must be written out in prose.

## Availability

Full seats on paid plans only. Organization admins approve and enable kits organization-wide. An individual design systems engineer cannot self-serve a private kit.

## Documented limitations — the important ones

- Kits cannot live in drafts; they must be relocated before publishing.
- **"Variable syntax extraction is simplified to CSS format, not preserved 1:1."** Your Figma variable structure does not survive intact.
- **"Only a subset of variables converts to global CSS values."** Not every Figma variable makes it into the generated style context. Multi-mode, aliased, or scoped variables are the likely casualties; expect to reconcile manually or document gaps in guidelines.

## Make attachments

Alongside kits, Make attachments bring project-specific context into prompts: PDFs, markdown, CSV/JSON datasets, screenshots, brand guidelines, legal copy, images, SVGs.

The stated problem: without them, designers summarized constraints verbally, producing idealized rather than production-ready prototypes. Attachments mean "real values reveal layout constraints and edge cases surface earlier" — an underrated capability, since feeding real data shapes makes generated components handle overflow, long strings, and empty states rather than the idealized three-word labels LLMs default to.

## The prototype-to-production claim

Figma documents a closed loop no other tool claims: build in Make against the real production package, then "deploy your Figma Make to production, using your production design system, using the Figma MCP Server." Prototype and production consume the identical package.`
  },
  {
    slug: 'figma-make-guidelines',
    title: 'Figma Make Guidelines: guidelines.md and the Context-Overload Warning',
    url: 'https://help.figma.com/hc/en-us/articles/33665861260823-Add-guidelines-to-Figma-Make',
    category: 'tools',
    system: 'Figma',
    tags: ['figma-make', 'guidelines', 'ai-generation', 'documentation', 'design-systems', 'context'],
    authority: 'primary',
    content: `# Add Guidelines to Figma Make

Guidelines are the baseline (non-kit) mechanism for constraining Figma Make generation. They "help Make generate better prototypes by providing instructions on coding behavior, personality, and style context usage."

## Method 1 — manual

Write directly in guidelines.md, or upload existing markdown:
- **Writing in Make:** Code > Guidelines folder > edit guidelines.md
- **Uploading:** drag .md files into the Guidelines folder; multiple files supported

Additional guidelines folders and files can be added by right-clicking the guidelines folder and choosing Create file or Create folder. This makes the mechanism structurally comparable to Lovable's .lovable/rules/ directory and Replit's .agents/skills/ tree — a nested markdown knowledge tree the agent consults.

## Method 2 — AI-generated

"Prompt Figma Make to analyze your npm packages and library styles and write comprehensive guidelines for you." Uses AI credits, may take several minutes. Make generates one or more markdown files covering components, styles, tokens, and general design system rules, which you then review and refine with specific use cases and edge cases.

This auto-generation path is a meaningful differentiator: rather than requiring design system teams to hand-author agent documentation, Make reads the package's component surface and the library's styles and drafts the guidelines itself, leaving humans to correct and add edge cases.

## Template structure

- General guidelines (layout, code practices)
- Design system guidelines (fonts, spacing, component rules)
- Component-specific details with usage and variants

## The key limitation, verbatim

**"More context isn't always better. It can confuse the LLM."**

Figma is explicitly warning against dumping an entire design system documentation site into guidelines. This is worth flagging to practitioners who assume more knowledge files means better adherence — and it sits in direct tension with the instinct to give an agent everything.

The convergent industry lesson across vendors: a thin always-loaded layer plus progressively-disclosed detail beats one large knowledge dump. Replit splits always-on custom instructions from on-demand skills for the same reason; Lovable splits the auto-generated schema from the hand-authored system.md.`
  },
  {
    slug: 'figma-make-package-requirements',
    title: 'Figma Make Package Requirements: React 18, Vite, and No Workspace Dependencies',
    url: 'https://developers.figma.com/docs/code/bring-your-design-system-package/',
    category: 'tools',
    system: 'Figma',
    tags: ['figma-make', 'npm', 'packaging', 'monorepo', 'react', 'vite', 'design-systems'],
    authority: 'primary',
    content: `# Bring Your Design System Package to Figma Make

The engineering contract for getting a real design system package into Figma Make. The requirements are stricter than the marketing implies.

## Runtime and build requirements

- **React 18**
- **Compatible with Vite**
- Must build successfully with Vite and React 18

The React 18 pin is a hard constraint. Systems already migrated to React 19, or built on Vue/Svelte/Angular/Web Components, are out. Figma Make's sandbox is a Vite + React 18 environment and your package must survive in it.

## Package distribution

- Public packages: published to the npm public registry
- Private packages: published to the organization's **Figma-maintained npm registry** (paid plans only)

The Figma-operated private registry is a notable architectural choice. Rather than asking teams to wire up Artifactory or GitHub Packages credentials (v0's and Lovable's approach), Figma runs the registry itself and gates it on org admin. Lower setup friction, but it means publishing a second copy of your design system into Figma's infrastructure alongside wherever it already lives.

## Vite configuration

- Babel plugins should be added to the plugin-react configuration
- Polyfills require @vitejs/plugin-legacy with configured targets

## Dependency management — the biggest practical blocker

**"Remove workspace dependencies"** — packages must not rely on the broader codebase ecosystem.

This is the requirement that breaks most enterprise design systems, which are typically monorepo packages depending on sibling workspace:* packages (a tokens package, an icons package, a utils package). You must produce a self-contained publishable artifact, bundling or inlining what was previously a workspace sibling.

- Public package dependencies are supported; Figma Make attempts automatic installation
- Private package scopes must not conflict with public registry scopes

## Module support

- "Most packages should work with your Make kit, including CommonJS modules"
- "Dynamic imports are generally supported," though runtime-generated import paths may cause issues

Component registries or icon systems that build import paths dynamically at runtime — e.g. import(\`./icons/\${name}\`) — are the documented failure mode.

## Private registry configuration

Organization admins manage scopes via the npm registry section in Resources. Configuration requires copying an .npmrc snippet generated during scope creation.

## Documentation gap worth knowing

The documentation does **not** specify requirements for entry points, CSS handling and extraction, tree-shaking, or TypeScript declaration files beyond the React/Vite baseline. For a component-library contract this is a meaningful gap — how CSS ships (imported stylesheet vs CSS-in-JS vs Tailwind preset) materially affects whether components render correctly in Make, and it is unspecified.`
  },
  {
    slug: 'replit-design-systems',
    title: 'Replit Design Systems: Custom Instructions, Skills, and Pinned Template Distribution',
    url: 'https://docs.replit.com/teams/custom-design-system',
    category: 'tools',
    system: 'Replit',
    tags: ['replit', 'ai-generation', 'design-systems', 'skills', 'agents', 'ai-tools', 'design-tokens'],
    authority: 'primary',
    content: `# Setting Up a Design System in Replit

An **Enterprise-only** feature configuring Agent with component libraries, brand assets, design tokens, and visual standards. "A design system gives Agent the knowledge it needs to build on-brand UI across everything your organization creates on Replit."

## Three configuration parts

**1. Custom Instructions** — custom_instruction/instructions.md holds high-level rules Agent always references, specifying which component library and design tokens to use. Always-on context.

**2. Skills** — in .agents/skills/, these provide detailed reference material Agent loads **on demand**: "component API documentation, theming guides, layout pattern libraries, and other deep reference content."

The always-on / on-demand split is Replit's answer to the context-overload problem: keep the instruction file thin, put the bulk behind progressive disclosure.

**3. Brand Assets** — logos, icons, fonts in a dedicated folder (e.g. src/assets/brand/) with Vite path aliases for clean imports like @brand/logo.svg.

## Skill file structure

    .agents/skills/your-design-system/
    ├── SKILL.md
    ├── references/
    │   ├── guides/
    │   └── components/
    └── packages/

SKILL.md acts as an **index** with sections for "General Guidance" and "Components," linking to individual markdown files documenting each component's props, variants, and usage examples. Note packages/ sits inside the skill directory — the tarball ships alongside its documentation as one unit.

## Ingestion

Create a Replit app and upload component library **tarfiles**; ask Agent to install packages and display all components; review for accuracy. The tarfile upload is the ingestion mechanism — not a registry connection, not a git source.

## Distribution

To distribute organization-wide, org admins **pin the design system app** via the three-dot menu, setting member access to **Read-only**.

Distribution is therefore by template app, not by dependency — every new project starts from a pinned app that already has the package installed and the skill present. This carries the same consequence as Lovable's file-copy model: existing projects do not get updates automatically.

## Validation checklist

- custom_instruction/instructions.md points to the skill
- Design tokens file is included
- Package is pre-installed in package.json

## Key limitation

Design systems apply only to "web apps, mobile apps, slides, and other artifacts" within the standard **pnpm monorepo structure** — unlike custom templates, which replace the entire stack. If your design system requires a different build setup, the design system feature will not carry it; you would need a custom template instead.

## Maintenance and drift risk

Token files should be updated when the design system ships new colors, spacing, or typography. Skills should be updated when components get new props, variants, or usage patterns. Two separate update surfaces to keep in sync — a built-in drift risk.

## Themes (all users)

Below the Enterprise tier, Replit offers themes: "Create and apply themes to your Agent applications. Update once, and watch every component transform instantly." Themes manage colors, fonts, and UI properties — token-level theming without component-library replacement. Replit incorporates the open-source TweakCN for customizing shadcn themes, so Replit themes are effectively shadcn CSS-variable theming with a GUI.`
  },
  {
    slug: 'replit-skills-scoping',
    title: 'Replit Agent Skills: SKILL.md Structure and Scoping Discipline',
    url: 'https://replit.com/blog/custom-skills',
    category: 'tools',
    system: 'Replit',
    tags: ['replit', 'skills', 'agents', 'ai-tools', 'context', 'design-systems'],
    authority: 'primary',
    content: `# Customize Replit Agent with Skills and Custom Instructions

Published June 2026.

## Custom Instructions

Always-on guidelines automatically injected into the agent's context across all projects. Workspace Settings → Customization. Available to **Pro and Enterprise** users — broader than the Enterprise-only design systems feature, so Pro users can approximate design system constraint through instructions alone.

## Skills

Activate conditionally when relevant tasks arise: "a skill only kicks in when a relevant task comes up."

Each skill is a folder containing SKILL.md plus supporting files. The main file has three components:

1. **Name** — short, lowercase identifier (e.g. api-design)
2. **Description** — determines when the agent uses the skill; **should specify when *not* to use it**
3. **Instructions** — rules, patterns, and things to avoid, in any format

The guidance that a description should state when *not* to fire is directly relevant to design systems: a design-system skill with an overbroad description will load on backend tasks, waste context, or crowd out a more specific skill.

## How skills load

- Automatically based on prompt relevance
- Manually via /skill-name syntax
- Selected from the "+" menu button

Manual /skill-name invocation matters for reliability — practitioners who find the skill isn't auto-firing can force it.

## The scoping principle, verbatim

**"Small, well-scoped skills combine cleanly. A skill that tries to cover everything tends to crowd out the skills that should have fired instead."**

This argues against one monolithic design-system skill and for splitting by concern — tokens, layout patterns, component APIs, accessibility — consistent with the references/guides/ and references/components/ subdivision in Replit's design system docs.

## Design system skill example

A design-system skill fires when someone builds UI, ensuring consistency across projects. The stated benefit: "the agent builds UI that fits your product, not a slightly different interpretation every time" — a concise statement of the drift problem every AI generator is attacking.`
  },
  {
    slug: 'ai-generators-design-system-comparison',
    title: 'How AI UI Generators Ingest Design Systems: Lovable vs v0 vs Figma Make vs Replit',
    url: 'https://docs.lovable.dev/features/design-systems',
    category: 'tools',
    tags: ['ai-tools', 'design-systems', 'comparison', 'lovable', 'v0', 'figma-make', 'replit', 'ai-generation'],
    authority: 'reference',
    content: `# How AI UI Generators Ingest Design Systems: A Comparison

Synthesis across the four tools' primary documentation, current as of August 2026. All four now have a real design system story — as recently as early 2025 only v0 did.

## The mechanisms differ architecturally

| Tool | Ingestion | Storage unit | Token source | Distribution |
|---|---|---|---|---|
| **Lovable** | Design system *is* a Lovable project; local source or npm wrapper | .lovable/ (design-system.json, system.md, rules/*.md) | src/index.css custom properties or tailwind.config, auto-discovered | **File copy** into src/design-system/<slug>/, recorded in lovable.toml |
| **v0** | GitHub repos (max 3) + Figma nodes + docs links + npm/.tgz | Design system as a **skill**, configured by v0.json | Inferred from package + consumer app; legacy path via tokens.css / Tailwind config | Referenced skill, attachable per-chat; team default |
| **Figma Make** | npm package (public or Figma-hosted private registry) + published Figma library variables + guidelines | **Make kit**, published org-wide | **Both** code tokens and Figma library variables/styles | Published kit appears in teammates' kit selector |
| **Replit** | Component library **tarfile** upload + Figma import | custom_instruction/instructions.md (always-on) + .agents/skills/<name>/SKILL.md (on-demand) | Design tokens file inside the skill; themes via shadcn CSS vars / TweakCN | **Pinned template app**, member access Read-only |

## The most important differentiator

**Figma Make is the only tool that reads tokens from the design source of truth.** Make kits ingest published Figma library variables and styles *alongside* the production npm package. Every other tool derives tokens from code only — Figma is a visual or screenshot input at best in v0 and Replit.

If a team's tokens live authoritatively in Figma variables, only Figma Make closes that loop without an export pipeline. Figma also claims the only prototype-to-production path: build in Make against the real package, then ship via the Figma MCP Server using the same components.

## The most important shared limitation

**All four are forward-only.** v0 states existing projects retain their original code and only new chats use updated design systems. Lovable requires accepting an update that overwrites local edits under src/design-system/. Replit distributes by pinned template, so existing apps don't inherit changes. Nobody solves design system version migration across already-generated apps.

## Gating is stratified

- Lovable design systems: **Enterprise-only**
- Replit design systems: **Enterprise-only** (Custom Instructions reach Pro)
- Figma Make kits: **Full seats on paid plans** plus **org admin approval** to publish
- v0 Design Systems 2.0: paid team plans for defaults, **Vercel Developer role** for private package env vars

No tool offers real design system import on a free or individual tier — prompt-level styling is the ceiling there.

## Everyone converged on React + Tailwind + shadcn, and it is a hard floor

Lovable supports "React-based component libraries out of the box" (Vue/Angular/Svelte require consultation). Make kits "exclusively support React-based codebases," pinned to React 18 and Vite. Replit and v0 are shadcn-derived.

Vercel states outright: "v0 is specifically trained on the default implementations of the shadcn/ui components and may struggle with any customizations" — the sharpest documented limitation in this space, and a trained-prior problem no config fixes.

Practitioners with non-React systems, React 19, or heavily customized shadcn forks should expect degraded results across the board.

## Nobody enforces at the component level

All four constrain generation through **prose guidelines plus available imports**. None can hard-fail a generation that hand-rolls a div instead of using your Button. Constraint is probabilistic everywhere.

## Two competing philosophies on context volume

Figma warns "more context isn't always better. It can confuse the LLM." Replit says "small, well-scoped skills combine cleanly. A skill that tries to cover everything tends to crowd out the skills that should have fired instead," and splits always-on instructions from on-demand skills. Lovable splits the auto-generated design-system.json/rules/ from the hand-authored, never-regenerated system.md.

The consistent lesson: a thin always-loaded layer plus progressively-disclosed detail beats one large knowledge dump.

## Auto-generation of agent-facing docs is becoming a category feature

Figma Make can "analyze your npm packages and library styles and write comprehensive guidelines for you." Lovable renders rules/components.md and rules/design-tokens.md from its schema. v0 reads the component surface from sources and builds a validating starter app.

Design system teams increasingly review AI-drafted agent documentation rather than authoring it — but every vendor still requires humans to supply the semantic layer (token hierarchy, quirks, constraints, when-not-to-use) that cannot be inferred from a type surface.`
  },
];

let written = 0;
for (const entry of ENTRIES) {
  const doc = {
    id: `aitools-batch-${entry.slug}`,
    title: entry.title,
    source: { type: 'url', location: entry.url, ingested_at: new Date().toISOString() },
    content: entry.content,
    chunks: [],
    metadata: {
      category: entry.category,
      tags: entry.tags,
      confidence: 'high',
      system: entry.system ?? '',
      source_url: entry.url,
      authority: entry.authority,
      research_batch: 'ai-generators-2026-08',
      last_updated: new Date().toISOString(),
    },
  };
  writeFileSync(join(OUT, `${entry.slug}.json`), JSON.stringify(doc, null, 2));
  written++;
}

console.log(`wrote ${written} staged entries`);
for (const e of ENTRIES) console.log(`  ${String(e.content.length).padStart(6)} chars  ${e.title.slice(0, 66)}`);
